
## Replay system paths
UTIL	:= $(HOME)/spec2.6/test
PREFIX	:= $(HOME)/glibc-2.5.1/prefix
BENCH	:= $(HOME)/spec2.6/bench

-include $(HOME)/.replay_build

CFLAGS := -static -static-libgcc -O3 -pthread -D_POSIX_C_SOURCE=200112
CFLAGS := $(CFLAGS) -Wall -W -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wdisabled-optimization
CFLAGS := $(CFLAGS) -Wpadded -Winline -Wpointer-arith -Wsign-compare -Wendif-labels
LDFLAGS :=-static -static-libgcc -lm

## NOREPLAY(original) CONFIGURATION
#CFLAGS	+= -DNOREPLAY_ENABLE

## REDUNDANCY(forked) CONFIGURATION
#CFLAGS	+= -DFORK_ENABLE

## SPEC(record/replay) CONFIGURATION
CFLAGS	+= -I$(UTIL) -I$(PREFIX)/include -DSPEC_ENABLE
LDFLAGS += -L$(PREFIX)/lib $(UTIL)/libutil.a

CC := gcc
BASEDIR := $(BENCH)/splash2/codes
MACROS := $(BASEDIR)/null_macros/c.m4.null.SPEC
M4 := m4 -s -Ulen -Uindex
x = *

$(TARGET): $(OBJS)
	$(CC) $(OBJS) $(CFLAGS) -o $(TARGET) $(LDFLAGS)

clean:
	rm -rf *.c *.h *.o $(TARGET)

.SUFFIXES:
.SUFFIXES:	.o .c .C .h .H

.H.h:
	$(M4) $(MACROS) $*.H > $*.h

.C.c:
	$(M4) $(MACROS) $*.C > $*.c

.c.o:
	$(CC) -c $(CFLAGS) $*.c

.C.o:
	$(M4) $(MACROS) $*.C > $*.c
	$(CC) -c $(CFLAGS) $*.c
